name: e-commerce-webapp

services:

  dev:
    env_file:
      - ./front_end/.env.dev
    build:
      context: ./front_end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./front_end/src
          target: /front_end/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./front_end/package.json
          target: /front_end/package.json
          
  user_db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: user_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  user_service:
    env_file: 
      - .env
    build:
      context: ./back_end
      dockerfile: user_service/Dockerfile
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DB_HOST=user_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8000
    ports:
      - "8000:8000"
  products_db:
    image: postgres:16
    ports:
     - 5434:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: products_db 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  products_service:
    env_file: 
      - .env
    build:
      context: ./back_end
      dockerfile: products_service/Dockerfile
    depends_on:
      products_db:
        condition: service_healthy
    environment:
      - DB_HOST=products_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8001
    ports:
      - "8001:8001"
  cart_db:
    image: postgres:16
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: cart_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d cart_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  cart_service:
    env_file: 
      - .env
    build:
      context: ./back_end
      dockerfile: cart_service/Dockerfile
    depends_on:
      cart_db:
        condition: service_healthy
    environment:
      - DB_HOST=cart_db 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8002
    ports:
      - "8002:8002"
  